### ISSUE TITLE
Can't update 1.5.0 to 1.5.2 (versionCode regression)

### ISSUE THREAD

**Issue by genericusername87** [lolo-io/OneList#106] opened 2024-10-11 21:04 UTC
I am unable to update 1List from v1.5.0 to v1.5.2 using your Github Releases.

The cause is that the APK for 1.5.2 has a smaller versionCode (=21) than 1.5.0 (=59). So Androids downgrade protection prevents the update.

Can you please recompile and reupload the APK for version 1.5.2 with a versionCode >59?

Thanks in advance!

**Comment by lolo-io** [comment] 2024-10-11 23:35
Oops, my bad, are you trying to install the app via the apk file shared in the release on github ?
I've just updated the release apk file, the versionCode is now higher than the previous one.

https://github.com/lolo-io/OneList/releases/tag/onelist-1.5.2

I will make sure in the future the shared apk, the fdroid build and the googlePLay build share the same versionCode. 
Feel free to close this issue if the problem is solved for you.

Thanks for noticing me the mistake ! 🙂

**Comment by genericusername87** [comment] 2024-10-12 16:24
Wow, that was incredibly fast! 
Yes, I meant the APK shared at the Github release :)

Thank you very much!

**Closed as completed** 2024-10-12 16:24 UTC
